---
title: "mean-variance-analysis"
author: "Sizhu Chen sc4248"
date: "April 26, 2018"
output: html_document
---

```{r }
#use 20130423 to 20160422 daily price
rty<-read.csv("spx50_20130423to20160422.csv",header = T)

ret<-log(rty[-1,]/rty[-nrow(rty),])#daily log return
ret<-exp(ret)-1#convert into daily net return

#Asset Allocation
library(MASS)
library(quadprog)

rf<-0.0101/252
```

```{r}
#50 stocks' portfolio

ret50<-ret

mu50 = colMeans(ret50)
sigma50 = cov(ret50)


muP50 = seq(min(mu50)+0.000001,max(mu50),length=200)  # target portfolio return
sdP50 = muP50 # sd of portfolio return

weight50 = matrix(0,nrow=200,ncol=50) # storage for portfolio weights
for (i in 1:length(muP50))  # find the optimal portfolios
{
  result = solve.QP(Dmat=2*sigma50,dvec=rep(0,50),
                    Amat=cbind(rep(1,50),mu50,diag(1,50)),
                    bvec=c(1,muP50[i],rep(0,50)),meq=2)
  sdP50[i] = sqrt(result$value)
  weight50[i,] = result$solution
}

par(mfrow = c(1,1))# draw efficient frontier
plot(sdP50,muP50,type="l",xlim=c(0,0.025),ylim=c(0,0.0025),lwd=2,col="steelblue",
     main = "Efficient Frontier of 50-stock Portfolio",
     ylab = "Expected Daily Return",
     xlab = "Risk")

ind1_50 = (sdP50 == min(sdP50))
points(sdP50[ind1_50],muP50[ind1_50],cex=1.1,pch="x")#MVP
text(sdP50[ind1_50]+0.0015,muP50[ind1_50],"MVP",cex=1)

points(0,rf,cex=1.1,pch="x") # show riskfree asset
text(0.001,rf,"Rf",cex=1)

ind2_50 = (muP50 > muP50[ind1_50])
lines(sdP50[ind2_50],muP50[ind2_50],type="l",xlim=c(0,.05),
      ylim=c(0,.0015),lwd=2,col="orange")#efficient frontier

sharpe50 =(muP50-rf)/sdP50 # Sharpe ratio
ind3_50 = (sharpe50 == max(sharpe50)) # find maximum Sharpe ratio
lines(c(0,1),rf+c(0,1)*sharpe50[ind3_50],lwd=1,lty=2,col="black") # line of optimal portfolios
points(sdP50[ind3_50],muP50[ind3_50],cex=1.1,pch="x")#tangent portfolio
text(sdP50[ind3_50]+0.004,muP50[ind3_50],"tangent portfolio",cex=1)

w50<-weight50[which.max(sharpe50),]#weight of 50 stocks
names(w50)<-colnames(ret50)

```

```{r }
#30 stocks' portfolio~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ret30<-ret[,1:30]

mu30 = colMeans(ret30)
sigma30 = cov(ret30)


muP30 = seq(min(mu30)+0.00001,max(mu30)-0.00001,length=200) 
sdP30 = muP30

weight30 = matrix(0,nrow=200,ncol=30) 
for (i in 1:length(muP30))
{
  result = solve.QP(Dmat=2*sigma30,dvec=rep(0,30),
                    Amat=cbind(rep(1,30),mu30,diag(1,30)),
                    bvec=c(1,muP30[i],rep(0,30)),meq=2)
  sdP30[i] = sqrt(result$value)
  weight30[i,] = result$solution
}
par(mfrow = c(1,1))
plot(sdP30,muP30,type="l",xlim=c(0,0.023),ylim=c(0,0.003),lwd=2,col="steelblue",
     main = "Efficient Frontier of 30-stock Portfolio",
     ylab = "Expected Daily Return",
     xlab = "Risk")
ind1_30 = (sdP30 == min(sdP30))

points(sdP30[ind1_30],muP30[ind1_30],cex=1.1,pch="x")
text(sdP30[ind1_30]+0.0015,muP30[ind1_30],"MVP",cex=1)

ind2_30 = (muP30 > muP30[ind1_30])
lines(sdP30[ind2_30],muP30[ind2_30],type="l",xlim=c(0,.05),
      ylim=c(0,.0015),lwd=3,col="orange")

points(0,rf,cex=1.1,pch="x") 
text(0.001,rf,"Rf",cex=1)

sharpe30 =(muP30-rf)/sdP30
ind3_30 = (sharpe30 == max(sharpe30)) 
lines(c(0,1),rf+c(0,1)*sharpe30[ind3_30],lwd=1,lty=2,col="black") 
points(sdP30[ind3_30],muP30[ind3_30],cex=1.1,pch="x")
text(sdP50[ind3_30]+0.004,muP50[ind3_30],"tangent portfolio",cex=1)

w30<-weight30[which.max(sharpe30),]#weight of 30 stocks
names(w30)<-colnames(ret30)

```

```{r}
#10 stocks' portfolio
ret10<-ret[,1:10]

mu10 = colMeans(ret10)
sigma10 = cov(ret10)

muP10 = seq(min(mu10)+0.00001,max(mu10)-0.00001,length=200) 
sdP10 = muP10 

weight10 = matrix(0,nrow=200,ncol=10) 
for (i in 1:length(muP10))  
{
  result = solve.QP(Dmat=2*sigma10,dvec=rep(0,10),
                    Amat=cbind(rep(1,10),mu10,diag(1,10)),
                    bvec=c(1,muP10[i],rep(0,10)),meq=2)
  sdP10[i] = sqrt(result$value)
  weight10[i,] = result$solution
}
par(mfrow = c(1,1))
plot(sdP10,muP10,type="l",xlim=c(0,0.03),ylim=c(0,0.002),lwd=2,col="steelblue",
     main = "Efficient Frontier of 10-stock Portfolio",
     ylab = "Expected Daily Return",
     xlab = "Risk") 
ind1_10 = (sdP10 == min(sdP10))
points(sdP10[ind1_10],muP10[ind1_10],cex=1.1,pch="x")
text(sdP10[ind1_10]+0.0015,muP10[ind1_10],"MVP",cex=1)
text(0.0012,rf,"Rf",cex=1)

ind2_10 = (muP10 > muP10[ind1_10])
lines(sdP10[ind2_10],muP10[ind2_10],type="l",xlim=c(0,.05),
      ylim=c(0,.0015),lwd=3,col="orange")

points(0,rf,cex=1.1,pch="x") 
sharpe10 =(muP10-rf)/sdP10 
ind3_10 = (sharpe10 == max(sharpe10))
lines(c(0,1),rf+c(0,1)*sharpe10[ind3_10],lwd=1,lty=2,col="black")
points(sdP10[ind3_10],muP10[ind3_10],cex=1.1,pch="x")
text(sdP10[ind3_10]+0.0045,muP10[ind3_10],"tangent portfolio",cex=1)

w10<-weight10[which.max(sharpe10),]
names(w10)<-colnames(ret10)


```

```{r}
#summary

expect.rtn10<-sum(w10*mu10)*252
expect.rtn30<-sum(w30*mu30)*252
expect.rtn50<-sum(w50*mu50)*252

risk10<-sdP10[which.max(sharpe10)]*sqrt(252)
risk30<-sdP30[which.max(sharpe30)]*sqrt(252)
risk50<-sdP50[which.max(sharpe50)]*sqrt(252)

summary.port<-data.frame(expected.annual.rtn=c(expect.rtn10,expect.rtn30,expect.rtn50),
                         Volatility=c(risk10,risk30,risk50)) 
rownames(summary.port)<-c("10-stock","30-stock","50-stock")

summary.port

```
```{r}
#compute sharpe ratio

rf<-0.0101
sharpe.ratio10<-(expect.rtn10-rf)/risk10
sharpe.ratio30<-(expect.rtn30-rf)/risk30
sharpe.ratio50<-(expect.rtn50-rf)/risk50
c(sharpe.ratio10,sharpe.ratio30,sharpe.ratio50)
```

```{r}
###~~~~~~~~~criteria~~~~~~~~~~~~~~~

### 1. Sharpe Ratio 
sharpe.rp<-sharpe.ratio50
sharpe.rp
```


```{r}
### 2. Treynor Ratio

mrk<-read.table("F-F_Research_Data_Factors_daily.txt",header = T)
mrk<-mrk[22959:23714,]#choose the corresponding period data
mrk$Rf<-as.numeric(levels(mrk$RF))[mrk$RF]
mrk$RM<-(mrk$Mkt.RF+mrk$Rf)*0.01#market daily return
mrk.var<-var(mrk$RM,na.rm = T)
std.M_with_all<-apply(ret50,2,cov,mrk$RM)

beta.i<-std.M_with_all/mrk.var
beta.p<-sum(w50*beta.i)

treynor.ratio<-(expect.rtn50-rf)/beta.p
treynor.ratio
```


```{r}
### 3.Jensen's alpha

RM<-mean(mrk$RM)*252
jensen.alpha<-expect.rtn50-rf-beta.p*(RM-rf)
jensen.alpha

```


```{r}
### 4. Fama French Model's alpha

FF<-read.table("F-F_Research_Data_Factors_daily.txt",header = T)
FF<-FF[which(rownames(FF)=="20130424"):which(rownames(FF)=="20160422"),]

port50.rtn<-apply(ret50,1,function(x){return(sum(w50*x))})# Rp
Rf<-as.numeric(levels(FF$RF))[FF$RF]
excess.rtn<-port50.rtn-Rf#Rp-Rf

fit1 <- lm(excess.rtn~FF$Mkt.RF+FF$SMB+FF$HML)
fit1$coefficients[1]
```

